#include <stdio.h>
typedef void TestFn(void);
typedef struct{
	char* name; 
	TestFn* fn;
} Test;

//code to be updated starts
TestFn setup,teardown,fixtureSetup,fixtureTearDown,test_fibonacci_returns_1_for_1,test_fibonacci_returns_0_for_0,test_fibonacci_returns_3_for_5,test_fibonacci_returns_0_for_negative_number,test_fibonacci_works_for_decimal,test_concat_concats_two_arrays_with_length_also,test_concat_concats_two_arrays_with_elements,test_concat_concats_gives_0_for_empty_array,test_filter_filters_the_array,test_filter_filters_the_array_,test_reverse_the_array_itself,test_reverses_array_to_new_array,test_slice_gives_portion_of_array,test_slice_doesnt_modifies_array,test_primeNumber_gives_number_of_prime_numbers_in_given_range,test_primeNumber_gives_array_of_prime_numbers_in_given_range,test_strCompare_gives_0_for_same_strings,test_strCompare_gives_negative_2_of_char_for_different_strings_of_same_length,test_strCompare_gives_5_of_char_for_different_strings_of_same_length,test_strCompare_gives_97_for_char_for_strings_of_different_length,test_strCompare_gives_10_for_different_chars_if_first_string_has_more_length,test_strCompare_gives_negative_99_for_different_chars_if_second_string_has_more_length,test_strCompare_gives_difference_for_space_in_string,test_strCompare_gives_difference_for_special_character,test_for_each_gives_4_for_3_,test_when_makesqr_is_passed_to_for_each_gives_square_of_array_elements,test_upper_case_gives_UPPERCASE_of_given_char,test__forEach_converts_to_upper_case_,test_giveMultiplesof5_gives_1_for_multiples_of_5,test_Filter_gives_multiples_of_5,test_str_len_returns_5_for_vikas,test_isCapital_gives_1_for_capital_letter,test_Filter_gives_filters_the_capital_letters,test_Filter_returns_string_that_greater_than_3,test_intMap_gives_double_of_each_elements_of_array,test_intMap_doesnot_changes_the_original_array,test_charMap_gives_ascii_value_of_characters,test_stringMap_gives_strings_length_of_evry_string,test_indexOf_gives_1_for_i_in_vikas,test_indexOf_gives_minus_1_for_j_in_vikas,test_indexof_gives_2_for_k_in_vikas;
Test test[] = {"test_fibonacci_returns_1_for_1",test_fibonacci_returns_1_for_1,"test_fibonacci_returns_0_for_0",test_fibonacci_returns_0_for_0,"test_fibonacci_returns_3_for_5",test_fibonacci_returns_3_for_5,"test_fibonacci_returns_0_for_negative_number",test_fibonacci_returns_0_for_negative_number,"test_fibonacci_works_for_decimal",test_fibonacci_works_for_decimal,"test_concat_concats_two_arrays_with_length_also",test_concat_concats_two_arrays_with_length_also,"test_concat_concats_two_arrays_with_elements",test_concat_concats_two_arrays_with_elements,"test_concat_concats_gives_0_for_empty_array",test_concat_concats_gives_0_for_empty_array,"test_filter_filters_the_array",test_filter_filters_the_array,"test_filter_filters_the_array_",test_filter_filters_the_array_,"test_reverse_the_array_itself",test_reverse_the_array_itself,"test_reverses_array_to_new_array",test_reverses_array_to_new_array,"test_slice_gives_portion_of_array",test_slice_gives_portion_of_array,"test_slice_doesnt_modifies_array",test_slice_doesnt_modifies_array,"test_primeNumber_gives_number_of_prime_numbers_in_given_range",test_primeNumber_gives_number_of_prime_numbers_in_given_range,"test_primeNumber_gives_array_of_prime_numbers_in_given_range",test_primeNumber_gives_array_of_prime_numbers_in_given_range,"test_strCompare_gives_0_for_same_strings",test_strCompare_gives_0_for_same_strings,"test_strCompare_gives_negative_2_of_char_for_different_strings_of_same_length",test_strCompare_gives_negative_2_of_char_for_different_strings_of_same_length,"test_strCompare_gives_5_of_char_for_different_strings_of_same_length",test_strCompare_gives_5_of_char_for_different_strings_of_same_length,"test_strCompare_gives_97_for_char_for_strings_of_different_length",test_strCompare_gives_97_for_char_for_strings_of_different_length,"test_strCompare_gives_10_for_different_chars_if_first_string_has_more_length",test_strCompare_gives_10_for_different_chars_if_first_string_has_more_length,"test_strCompare_gives_negative_99_for_different_chars_if_second_string_has_more_length",test_strCompare_gives_negative_99_for_different_chars_if_second_string_has_more_length,"test_strCompare_gives_difference_for_space_in_string",test_strCompare_gives_difference_for_space_in_string,"test_strCompare_gives_difference_for_special_character",test_strCompare_gives_difference_for_special_character,"test_for_each_gives_4_for_3_",test_for_each_gives_4_for_3_,"test_when_makesqr_is_passed_to_for_each_gives_square_of_array_elements",test_when_makesqr_is_passed_to_for_each_gives_square_of_array_elements,"test_upper_case_gives_UPPERCASE_of_given_char",test_upper_case_gives_UPPERCASE_of_given_char,"test__forEach_converts_to_upper_case_",test__forEach_converts_to_upper_case_,"test_giveMultiplesof5_gives_1_for_multiples_of_5",test_giveMultiplesof5_gives_1_for_multiples_of_5,"test_Filter_gives_multiples_of_5",test_Filter_gives_multiples_of_5,"test_str_len_returns_5_for_vikas",test_str_len_returns_5_for_vikas,"test_isCapital_gives_1_for_capital_letter",test_isCapital_gives_1_for_capital_letter,"test_Filter_gives_filters_the_capital_letters",test_Filter_gives_filters_the_capital_letters,"test_Filter_returns_string_that_greater_than_3",test_Filter_returns_string_that_greater_than_3,"test_intMap_gives_double_of_each_elements_of_array",test_intMap_gives_double_of_each_elements_of_array,"test_intMap_doesnot_changes_the_original_array",test_intMap_doesnot_changes_the_original_array,"test_charMap_gives_ascii_value_of_characters",test_charMap_gives_ascii_value_of_characters,"test_stringMap_gives_strings_length_of_evry_string",test_stringMap_gives_strings_length_of_evry_string,"test_indexOf_gives_1_for_i_in_vikas",test_indexOf_gives_1_for_i_in_vikas,"test_indexOf_gives_minus_1_for_j_in_vikas",test_indexOf_gives_minus_1_for_j_in_vikas,"test_indexof_gives_2_for_k_in_vikas",test_indexof_gives_2_for_k_in_vikas};
char testFileName[] = {"pointerTest.c"};
void _setup(){/*CALL_SETUP*/}
void _teardown(){/*CALL_TEARDOWN*/}
void fixtureSetup(){}
void fixtureTearDown(){}
//code to be updated ends

int testCount;
int passCount;
int currentTestFailed;

int assert_expr(int expr, const char* fileName, int lineNumber, const char* expression){
	if(expr) return 0;
	currentTestFailed = 1;
	printf("\t\t %s : failed at %s:%d\n",expression, fileName,lineNumber);
	return 1;
}
int assert_equal(int val1, int val2, const char* fileName, int lineNumber,const char* expr1,const char* expr2){
	if(val1 == val2) return 0;
	currentTestFailed = 1;
	printf("\t\t %d == %d: failed in assertEqual(%s,%s) at %s:%d\n",val1,val2,expr1,expr2, fileName,lineNumber);
	return 1;
}

void runTest(char* name, TestFn test){
	testCount++,currentTestFailed=0;
	printf("\t%s\n",name);
	_setup();
		test();
	_teardown();
	if(!currentTestFailed) passCount++;	
}

int main(){
	int i,total = sizeof(test)/sizeof(Test);
	fixtureSetup();
	testCount=0,passCount=0;
	printf("********* Starting tests of %s\n\n",testFileName);
	for (i = 0; i < total; ++i)
		runTest(test[i].name,test[i].fn);
	printf("\n********* Ran %d tests passed %d failed %d\n",testCount,passCount,testCount-passCount);
	fixtureTearDown();
	return 0;
}